models.py
import datetime
from flask_bcrypt import generate_password_hash
from flask_login import UserMixin
from peewee import IntegrityError, ForeignKeyField, CharField, BooleanField, DateTimeField, TextField

from base_model import BaseModel, sql_db


class User(UserMixin, BaseModel):
    username = CharField(unique=True)
    email = CharField(unique=True)
    password = CharField(max_length=100)
    joined_at = DateTimeField(default=datetime.datetime.now)
    is_admin = BooleanField(default=False)

    class Meta:
        order_by = ('-joined_at',)

    def following(self):
        return (
            User.select().join(
                Relationship, on=Relationship.to_user
            ).where(
                Relationship.from_user == self
            )

        )

    def followers(self):
        return (
            User.select().join(
                Relationship, on=Relationship.from_user
            ).where(
                Relationship.to_user == self
            )
        )

    def get_posts(self):
        return Post.select().where(Post.user == self)

    def get_stream(self):
        return Post.select().where(
            (Post.user << self.following()) |
            (Post.user == self)
        )

    @classmethod
    def create_users(cls, username, email, password, admin=False):
        try:
            with sql_db.transaction():
                cls.create(
                    username=username,
                    email=email,
                    password=generate_password_hash(password),
                    is_admin=admin
                )
        except IntegrityError:
            raise ValueError('User Already Exists')


class Post(BaseModel):
    timestamp = DateTimeField(default=datetime.datetime.now)
    user = ForeignKeyField(
        model=User,
        related_name='posts'
    )
    content = TextField()

    class Meta:
        order_by = ('-timestamp',)


class Relationship(BaseModel):
    from_user = ForeignKeyField(model=User, related_name='relationships')
    to_user = ForeignKeyField(model=User, related_name='related_to')

    class Meta:
        indexes = ((('from_user', 'to_user'), True),)

forms.py
from flask_wtf import Form
from wtforms import StringField, PasswordField, TextAreaField
from wtforms.validators import (DataRequired, Regexp, ValidationError, Email,
                                Length, EqualTo)
from models import User


def name_exists(form, field):
    if User.select().where(User.username == field.data).exists():
        raise ValidationError('User already exists')


def email_exists(form, field):
    if User.select().where(User.email == field.data).exists():
        raise ValidationError('Email associated with this user  already exists')


class RegistrationForm(Form):
    username = StringField('Username', validators=[  # Username is the placeholder/Label for the form
        DataRequired(),
        Regexp(r'^[a-zA-Z0-9_]+$', message='User should be one word with letters numbers and underscore only'),
        name_exists])
    email = StringField('Email', validators=[DataRequired(), Email(), email_exists])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6),
                                                     EqualTo('password2', message='Passwords must be matched')])
    password2 = PasswordField('Confirm Password', validators=[DataRequired()])


class LoginForm(Form):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])


class PostForm(Form):
    content = TextAreaField('Whats on your mind', validators=[DataRequired()])

app.py
import os

from flask import g
from flask_login import current_user

from application_factory import create_app
from base_model import sql_db


CONFIG_NAME = os.getenv('APP_SETTINGS', 'config.DevelopmentConfig')
app = create_app(CONFIG_NAME)


@app.before_request
def before_request():
    g.db = sql_db
    g.db.connect()
    g.user = current_user


@app.teardown_request
def teardown_request(response):
    g.db.close()
    return response


if __name__ == '__main__':
    app.run(use_reloader=True)

views.py
from flask import render_template, flash, redirect, url_for, abort, g, Flask, app, Blueprint
from flask_bcrypt import check_password_hash
from flask_login import current_user, login_user, login_required, logout_user
from peewee import DoesNotExist, IntegrityError

import forms
from models import User, Post, Relationship

social = Blueprint('social', __name__)


@social.route('/register', methods=('GET', 'POST'))
def register():
    form = forms.RegistrationForm()
    if form.validate_on_submit():
        flash('Registration Succesful', 'success')
        User.create_users(
            username=form.username.data,
            email=form.email.data,
            password=form.password.data
        )
        return redirect(url_for('social.index'))
    return render_template('register.html', form=form)


@social.route('/login', methods=('GET', 'POST'))
def login():
    form = forms.LoginForm()
    if form.validate_on_submit():
        try:
            user = User.get(User.email == form.email.data)
        except DoesNotExist:
            flash('Your email or Password doesnt match', 'error')
        else:
            if check_password_hash(user.password, form.password.data):
                login_user(user)  # creating sessions on users browser and giving the cookie
                flash('You are logged in', 'success')
                return redirect(url_for('social.index'))
            else:
                flash('Your email or Password doesnt match', 'error')
    return render_template('login.html', form=form)


@social.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You are Logged Out', 'success')
    return redirect(url_for('social.index'))


@social.route('/')
def index():
    stream_ = Post.select().limit(100)
    return render_template('stream.html', stream=stream_)


@social.route('/new_post', methods=('GET', 'POST'))
@login_required
def post():
    form = forms.PostForm()
    if form.validate_on_submit():
        Post.create(user=g.user._get_current_object(),
                    content=form.content.data.strip())
        flash('Message Posted', 'success')
        return redirect(url_for('social.index'))
    return render_template('post.html', form=form)


@social.route('/stream')
@social.route('/stream/<username>')
@login_required
def stream(username=None):
    template = 'stream.html'
    if username and username != current_user.username:
        try:
            user = User.select().where(User.username ** username).get()
        except DoesNotExist:
            abort(404)
        else:
            stream = user.posts.limit(100)
    else:
        stream = current_user.get_stream().limit(100)
        user = current_user
    if username:
        template = 'user_stream.html'
    return render_template(template, stream=stream, user=user)


@social.route('/post/<int:post_id>')
def view_post(post_id):
    posts = Post.select().where(Post.id == post_id)
    if posts.count() == 0:
        abort(404)
    return render_template('stream.html', stream=posts)


@social.route('/follow/<username>')
@login_required
def follow(username):
    try:
        to_user = User.get(User.username ** username)
    except DoesNotExist:
        abort(404)
    else:
        try:
            Relationship.create(
                from_user=g.user._get_current_object(),
                to_user=to_user
            )
        except IntegrityError:
            pass
        else:
            flash('You are now following {}!'.format(to_user.username), 'success')
    return redirect(url_for('social.stream', username=to_user.username))


@social.route('/unfollow/<username>')
@login_required
def unfollow(username):
    try:
        to_user = User.get(User.username ** username)  # find the user
    except DoesNotExist:
        pass
    else:
        try:
            Relationship.get(
                from_user=g.user._get_current_object(),
                to_user=to_user
            ).delete_instance()
        except IntegrityError:
            pass
        else:
            flash('You have unfollowed {}!'.format(to_user.username), 'success')
    return redirect(url_for('social.stream', username=to_user.username))

templates/layout.html
<!DOCTYPE html>
<html class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}Be Social{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/static/css/normalize.min.css" , rel="stylesheet" , type="text/css">
    <link rel="stylesheet" href="/static/css/main.css" rel="stylesheet" , type="text/css">
    <script src="/static/js/main.js"></script>

    <!--[if lt IE 9]>
            <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
            <script>window.html5 || document.write('<script src="/static/js/vendor/html5shiv.js"><\/script>')</script>
        <![endif]-->
</head>
<body>

<header>

    <div class="row">

        <div class="grid-33">

            <a href="{{ url_for('social.index') }}" class="icon-logo"></a>

        </div>

        <div class="grid-33">

            <!-- Say Hi -->
            <h1>Hello {% if current_user.is_authenticated %}{{ current_user.username }}{% endif %}!</h1>


        </div>

        <div class="grid-33">

            <!-- Log in/Log out -->
            {% if current_user.is_authenticated %}
                <a href="{{ url_for('social.logout') }}" class="icon-power" title="Log Out"> </a>
            {% else %}
                <a href="{{ url_for('social.login') }}" class="icon-power" title="Log In"></a>
                <a href="{{ url_for('social.register') }}" class="icon-profile" title="Register"></a>
            {% endif %}

        </div>

    </div>

</header>

<!-- Flash messages -->
{% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="notification {{ category }}">{{ message }}</div>
        {% endfor %}
    {% endif %}
{% endwith %}

<div class="row">

    <div class="main">

        <nav>

            <a href="{{ url_for('social.index') }}">Go Home!</a>
            {% if current_user.is_authenticated %}
                <a href="{{ url_for('social.stream',username=current_user.username) }}">Following</a>
                <a href="{{ url_for('social.post') }}" class="new">Create New Post</a>
            {% endif %}

        </nav>

        {% block content %}{% endblock %}

    </div>

</div>

<footer>

    <div class="row">

        <p>Pythonic</p>

    </div>

</footer>

<script src="/js/vendor/disTime.min.js"></script>
<script src="/js/main.js"></script>

</body>
</html>

templates/login.html
{% extends 'layout.html' %}
{% from 'macros.html' import render_field %}
{% block content %}
<form method="POST" action="" class="form">
{{ form.hidden_tag() }}
{#allows you to hiddent tag from the code == it
creates a div that has a style attribute of hidden, and it will put the hidden tags inside the code #}
{% for field in form %}
{# this part is connected from macro macros.html #}
    {{ render_field(field) }}
{% endfor %}
<button type="submit" id="submit">Login!</button>
</form>
{% endblock %}

templates/macros.html
{% macro render_field(field) %} {# render_field is the name given its not default you can choos anyone for macro  #}
    <div class="field">
        {% if field.errors %}
            {% for error in field.errors %}
                <div class="Notification Error">{{ error }}</div>
            {% endfor %}
        {% endif %}
        {{ field(placeholder=field.label.text) }}  {# Grabing the placeholder from the form #}
    </div>
{% endmacro %}

templates/post.html
{% extends 'layout.html' %}
{% from 'macros.html' import render_field %}
{% block content %}
<form method="POST" action="">
{{ form.hidden_tag() }}
{% for field in form %}
    {{ render_field(field) }}
{% endfor %}
<button type="submit" id="submit">Post</button>
</form>
{% endblock %}

templates/register.html
{% from 'macros.html' import render_field %}
<form method="POST" action="" class="form">
{{ form.hidden_tag() }}
{#allows you to hiddent tag from the code == it
creates a div that has a style attribute of hidden, and it will put the hidden tags inside the code #}
{% for field in form %}
{# this part is connected from macro macros.html #}
    {{ render_field(field) }}
{% endfor %}
<button type="submit" id="submit">Register</button>
</form>

templates/stream.html
{% extends 'layout.html' %}
{% block content %}
{% for post in stream %}
    <article>
    <h2>
    <a href="{{ url_for('social.stream', username=post.user.username) }}">{{ post.user.username }}</a>
</h2>
<i class="clock"></i><time data-time="{{ post.timestamp }}" class="distime" datetime="{{
 post.timestamp.strftime('%Y-%m-%d %H:%M:%S')}}">{{ post.timestamp.strftime('%Y-%m-%d %H:%M:%S')}}</time><a href="{{ url_for('social.view_post',post_id=post.id) }}" class="view">View</a>
 <div class="post">
 {{ post.content }}
 </div>
</article>
{% endfor %}
{% endblock %}

templates/user_stream.html
{% extends 'stream.html' %}
{% block content %}
<div class="row">
    <div class="grid-25">
        <h1>{{ user.username }}</h1>
    </div>
    <div class="grid-50">
        <div class="grid-33">
            <h5>Posts</h5>
            <p>{{ user.posts.count() }}</p>
        </div>

        <div class="grid-33">
            <h5>Followers</h5>
            <p>{{ user.followers().count() }}</p>
        </div>

        <div class="grid-33">
            <h5>Following</h5>
            <p>{{ user.following().count() }}</p>
        </div>
        <div class="grid-25">
        {# Follow/Unfollow     button   #}

        {% if current_user.is_authenticated %} {#        {%  %}#}
            {% if user != current_user %}  {#    if its not current user    {%  %}#}
                {% if not user in current_user.following() %}   {#   if the user is not already been followed by logged in user
                      {%  %}#}
                      <a href="{{ url_for('social.follow', username=user.username) }}" class="small">Follow</a>
                {% else %}
                    <a href="{{ url_for('social.unfollow', username=user.username) }}" class="small">Unfollow</a>
                {% endif %}
            {% endif %}
        {% endif %}
        </div>
    </div>
</div>
{#super will gives the content of the block from the parent#}
{{ super() }}
{% endblock %}